### ISSUE TITLE
so amm the shader have a problem in the water the water waves are gone just gone and the water caustics godray are to noised and the vanilla shadows are still there here some images

### ISSUE THREAD

**Issue by MrDeathKMGamer** [zombye/spectrum#2] opened 2022-04-18 15:58 UTC
![2022-04-18_18 54 22](https://user-images.githubusercontent.com/88420078/163835978-ad64d700-d12e-4750-a7fa-359bebbd646a.png)
![2022-04-18_18 54 25](https://user-images.githubusercontent.com/88420078/163835992-7ada794c-e582-40f9-9d94-cf76691ad985.png)
![2022-04-18_18 54 39](https://user-images.githubusercontent.com/88420078/163836003-4ca0188d-dff4-4583-b9a2-6be85a91cc95.png)
![2022-04-18_18 54 50](https://user-images.githubusercontent.com/88420078/163836012-9aac6190-b441-4a51-a001-9b876158ae33.png)

**Comment by zombye** [comment] 2022-11-27 16:07
The missing water waves should be fixed after commit 846b09c.

The vanilla entity shadows still being rendered is likely caused by an incompatible mod. I could not reproduce their presence.

The underwater godrays being noisy is expected, and an intentional tradeoff for some extra performance.
The noise can be mitigated by raising "VL Steps" in "Shader Options" -> "Water Fog". This has a performance cost, though an optimization for the effect is planned which should allow a decent improvement at similar performance.

**Closed as completed by zombye** 2022-11-27 16:07 UTC
